name: build

on: [pull_request]

jobs:
  macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: 'build macos'
      run: make all


  ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: 'build ubuntu'
      env:
        CC: clang
      run: make all
